version: '3'
services:
  sisito:
    build:
      context: .
      dockerfile: Dockerfile.sisito
    ports:
     - '3000:3000'
     - '11080:1080'
  mysql:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Tokyo
  postfix:
    build:
      context: .
      dockerfile: Dockerfile.postfix
  sisito_api:
    build:
      context: .
      dockerfile: Dockerfile.sisito-api
    ports:
     - '8080:8080'
